name: open-search-engine
networks:
    open_search_engine_network:
        driver: bridge
services:
    mongo:
        build:
            dockerfile: .docker/mongo/Dockerfile
        container_name: open-search-engine-mongo-db
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
            MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
        ports:
            - '${MONGO_PORT}:27017'
        command: --replSet rs0 --keyFile /etc/mongo-keyfile --bind_ip_all --port 27017
        healthcheck:
            test: echo "
                try { rs.status() }
                catch (err) {
                    rs.initiate({
                        _id:'rs0',
                        members:[
                            { _id:0, host:'127.0.0.1:27017' }
                        ]
                    })
                }" | mongosh --port 27017 -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin
            interval: 5s
            timeout: 15s
            start_period: 15s
            retries: 10
        networks:
            - open_search_engine_network
        volumes:
            - mongo_dist:/data/db
    ollama:
        image: ollama/ollama:0.3.12
        container_name: open-search-engine-ollama
        ports:
            - '11434:11434'
        volumes:
            - ollama_dist:/root/.ollama
        networks:
            - open_search_engine_network
    qdrant:
        image: qdrant/qdrant:v1.11.5
        container_name: open-search-engine-qdrant
        ports:
            - '6333:6333'
            - '6334:6334'
        volumes:
            - qdrant_storage:/qdrant/storage:z
        networks:
            - open_search_engine_network
volumes:
    mongo_dist:
    ollama_dist:
    qdrant_storage:
