// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package products

import (
	"github.com/hainguyen27798/open-search-engine/internal/domain/products/repos"
	"github.com/hainguyen27798/open-search-engine/internal/domain/products/services"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// Injectors from product_wire.go:

func InitProductHandler(database *mongo.Database) (*ProductController, error) {
	iProductRepo := repos.NewProductRepo(database)
	iProductService := services.NewProductService(iProductRepo)
	productController := NewProductController(iProductService)
	return productController, nil
}
