// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wires

import (
	"github.com/hainguyen27798/open-typesense-search/internal/controllers"
	"github.com/hainguyen27798/open-typesense-search/internal/repos"
	"github.com/hainguyen27798/open-typesense-search/internal/services"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// Injectors from product_admin_wire.go:

func InitProductAdminHandler(database *mongo.Database) (*controllers.ProductAdminController, error) {
	iProductRepo := repos.NewProductRepo(database)
	iProductAdminService := services.NewProductAdminService(iProductRepo)
	productAdminController := controllers.NewProductAdminController(iProductAdminService)
	return productAdminController, nil
}
